// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Resharper.Paket.CSharp")]
[assembly: AssemblyProductAttribute("Resharper.Paket")]
[assembly: AssemblyDescriptionAttribute("Plugin for ReSharper to support Paket references correctly")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
